name: Football Bot 24/7

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # restart every 5 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install deps
        run: |
          pip install python-telegram-bot requests
          
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python bot.py